### PR TITLE
Update PSI-MS.obo derived cv.cpp and cv.hpp

### PR DESCRIPTION
**Pull request by sneumann**

### CODE REVIEW

**Comment by lgatto** [comment]
Thanks, Steffen. Are you waiting for somebody to merge? Or just go ahead.

**Comment by jorainer** [comment]
There are still some failing tests that have to be fixed.

**Comment by lgatto** [comment]
Weird!?! Travis isn't complaining. Are there tests that are run only locally?

**Comment by sneumann** [comment]
Before merging I'd like someone to confirm that this fixes https://github.com/sneumann/mzR/issues/170
Or even better, we get a unit test checking for #170 . I have no idea here how to (easily) reproduce. Yours, Steffen

**Comment by shubham1637** [comment]
I tried to install this update, but couldn't install the package.
`install_github("sneumann/mzR", ref = "feature/updateCV20191015")`

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'ProtGenerics' 1.14.0 is being loaded, but >= 1.17.3 is required
ERROR: lazy loading failed for package 'mzR'
* removing 'C:/Users/shubh/Documents/R/win-library/3.5/mzR'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/shubh/AppData/Local/Temp/RtmpQ1WXbh/file19687571659f/mzR_2.19.8.tar.gz’ had non-zero exit status
```
I have R version 3.5.1

**Comment by lgatto** [comment]
@shubham1637 - you will need a more recent version of R to get the latest Bioconductor packages (for instance `ProtGenerics`).

**Comment by shubham1637** [comment]
I tried again on R version 3.6.1. Same error
```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘ProtGenerics’ 1.16.0 is being loaded, but >= 1.17.3 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘mzR’
* removing ‘/home/shubham/R/x86_64-pc-linux-gnu-library/3.6/mzR’
Error: Failed to install 'mzR' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpi4EULF/fileeac696ba4e8/mzR_2.19.8.tar.gz’ had non-zero exit status
```

**Comment by lgatto** [comment]
You will also need the [development version of Bioc](http://bioconductor.org/developers/how-to/useDevel/) (which is only available with the very latest version of R). I'm testing it at the moment.

**Comment by lgatto** [comment]
```r
BiocManager::install("sneumann/mzR", ref = "feature/updateCV20191015")
```
builds fine on:
```r
> sessionInfo()
R version 3.6.1 Patched (2019-09-14 r77192)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1   
```

**Comment by sneumann** [comment]
Maybe this also fixes #215

**Pull request merged**
