### PR TITLE
Fix build on Fedora 38 / R-4.3.0

### PR DESCRIPTION
**Pull request by c4chris**
As suggested in issue #282

### CODE REVIEW

**Comment by c4chris** [comment]
somebody needs to approve the workflow so that we can see if the build succeeds in the CI framework

**Comment by sneumann** [comment]
Hi, the CI is broken, I'll fix that independently. Thanks for the PR, yours, Steffen

**Comment by c4chris** [comment]
Thanks :)

**Comment by sneumann** [comment]
Ich habe zu danken ! Gruss, Steffen

**Pull request merged**
