### PR TITLE
Add scanWindowLowerLimit and scanWindowUpperLimit to header

### PR DESCRIPTION
**Pull request by jorainer**
- Add scanWindowLowerLimit and scanWindowUpperLimit variables.
- Export scanWindowLowerLimit and scanWindowUpperLimit to mzML (issue #202).
- Update and amend documentation and unit tests accordingly.

### CODE REVIEW

**Comment by jorainer** [comment]
@sneumann or @lgatto , this fixed issue #202 - if you're OK with it you can go ahead and merge.

**Comment by lgatto** [comment]
Fine by me.

**Comment by lgatto** [comment]
Oh, and let me known if/when to push to Bioc if you don't have access.

**Comment by sneumann** [comment]
Looks good to me!

**Comment by sneumann** [comment]
Pushed `upstream`. YOurs, Steffen

**Pull request merged**
