### PR TITLE
Check how to Pwiz upgrade

### PR DESCRIPTION
**Pull request by sneumann**
I don't really understand why this includes 359 commits. 
That seems more than what we should have

### CODE REVIEW

**Comment by thirdwing** [comment]
I think we can squash all commits when merging, so it doesn't matter.

Let's delete the master branch and make devel as the default then.

**Comment by lgatto** [comment]
> Let's delete the master branch and make devel as the default then.

I am not sure this is a good idea. Have you tried the tried the `-s`/`-X` options, specifying `theirs` (or `ours` depending to direction) to keep all commits from one branch?

**Comment by thirdwing** [comment]
As I understand, `devel` branch is more like a `release` branch since it is synced with BioC SVN.

Let's keep our master branch, but we need to make sure all changes in `devel` branch reflect in `master` branch.

**Comment by lgatto** [comment]
> As I understand, `devel` branch is more like a release branch since it is synced with BioC SVN.

Yes, that's how I work: `devel` is the official development code base, and `release-3.3` is the official release code base, both a in sync with Bioc svn. Do you want me to try to get `master` and `pwiz_upgrade` synced, and then merge into `devel` and `dcommit` to Bioc svn?

**Comment by thirdwing** [comment]
I think we need to merge pwiz_upgrade into master first, then the master
branch will have all the commits.

On Mon, May 30, 2016 at 5:25 PM, Laurent Gatto <notifications@github.com>
wrote:

> As I understand, devel branch is more like a release branch since it is
> synced with BioC SVN.
>
> Yes, that's how I work: devel is the official development code base, and
> release-3.3 is the official release code base, both a in sync with Bioc
> svn. Do you want me to try to get master and pwiz_upgrade synced, and
> then merge into devel and dcommit to Bioc svn?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sneumann/mzR/pull/43#issuecomment-222556360>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABebVWT3umoxJJHHfA-hh-W0YSdq5T7rks5qG1XhgaJpZM4IpIu5>
> .
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by lgatto** [comment]
I have merged `master` and `pwiz_upgrade`. Checking locally now before pushing and `dcommit` to `devel`. I close this PR.

**Comment by thirdwing** [comment]
I think I have messed things up. The `pwiz` in the master branch might not be the latest version.

**Comment by lgatto** [comment]
Ok, I haven't committed to svn yet. Let me know when/where I can merge again.

**Comment by thirdwing** [comment]
Right now `master` branch has the latest version of `pwiz` and it passed R CMD check on Linux.

I am not sure it will pass on Windows or not.

**Comment by sneumann** [comment]
http://bioconductor.org/spb_reports/mzR_2.7.4_buildreport_20160601175849.html
so we still have the windows build error due to the netcdf

**Comment by thirdwing** [comment]
Many `undefined reference to _Unwind_SjLj_Resume` errors.

This indicates the toolchain compiled `libpwiz.a` is not the same with the toolchain used by BioC.

**Pull request closed without merging**
