### PR TITLE
Feature removelibnet cdf

### PR DESCRIPTION
**Pull request by sneumann**
Changes remove netCDF files from /src, change from `.C()` calls to using ncdf4

### CODE REVIEW

**Comment by jotsetung** [comment]
Note: something in this pull request breaks one of MSnbase's unit tests:

```
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
   - 129.1378 +/- 0.002 (#B3DE69)
   - 130.1348 +/- 0.002 (#FCCDE5)
   - 130.1411 +/- 0.002 (#D9D9D9)
   - 131.1382 +/- 0.002 (#BC80BD)
  Object of class "Spectrum1"
   Retention time: 0:0 
   MSn level: 1 
   Total ion count: 684 
   Polarity: 1 
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 2067 SKIPPED: 8 FAILED: 1
  1. Failure: adding compatible ident with mzID and mzR (@test_id.R#27) 
  
  Error: testthat unit tests failed
  Execution halted
```

@lgatto , eventually you could have a look at that?

**Comment by sneumann** [comment]
That message is also part of the error report in 
http://bioconductor.org/checkResults/devel/bioc-LATEST/MSnbase/tokay1-checksrc.html
(but there on windows only ?!) so not directly related to the netCDF changes. Yours, Steffen

**Comment by jotsetung** [comment]
Agree, that error (see below) seems to be completely unrelated to CDF. I checked and it was introduced with commit https://github.com/sneumann/mzR/commit/5f136a28b44ded16f1bf498b6cdc8e2d9107b60e ; with mzR from https://github.com/sneumann/mzR/commit/8d43866ca7a9ac22e2444d03030ac10518ecf112 `R CMD check` of `MSnbase` runs without problems.

```r
>      quantFile <- dir(system.file(package = "MSnbase", dir = "extdata"),
+                       full.name = TRUE, pattern = "mzXML$")
>      identFile <- dir(system.file(package = "MSnbase", dir = "extdata"),
+                       full.name = TRUE, pattern = "dummyiTRAQ.mzid")     
>      msexp0 <- readMSData(quantFile)
>      id1 <- mzR::openIDfile(identFile)
>      msexp1 <- addIdentificationData(msexp0, id1)
>      id2 <- mzID::mzID(identFile)
reading dummyiTRAQ.mzid... DONE!
>      msexp2 <- addIdentificationData(msexp0, id2)
> 
>      ## same feature variables are equal
>      k <- intersect(fvarLabels(msexp1), fvarLabels(msexp2))     
>      expect_equal(fData(msexp1)[, k], fData(msexp2)[, k])
Error: fData(msexp1)[, k] not equal to fData(msexp2)[, k].
Component “scan.number.s.”: Modes: character, numeric
Component “scan.number.s.”: target is character, current is numeric

```

**Comment by jotsetung** [comment]
I'm OK with merging - I'll make a new issue regarding the error that was introduced previously.

**Comment by sneumann** [comment]
Hi, with Johannes' OK I'll merge and no need for Laurent to review anymore, 
but there is no special button to un-invite reviewers ... Thanks, Steffen

**Pull request merged**
