### PR TITLE
Add filterString support

### PR DESCRIPTION
**Pull request by sgibb**
This is a PR to implement *filter string* support. Please consider it as WIP.
See https://github.com/lgatto/MSnbase/issues/278 for details.

### CODE REVIEW

**Comment by sgibb** [comment]
This works for pwiz (I didn't update the unit test yet); copy write examples fail.

I am wondering whether `can.cvParam(MS_filter_string).value` is the correct way to extract the *filter string* or should we extend the `ScanHeaderStruct`?

**Comment by jotsetung** [comment]
I guess `scan.cvParam(MS_filter_string).value` should be OK. You could use the `msdata/proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz` file to see whether it returns the string in the respective unit test as @sneumann suggested.

**Comment by jotsetung** [comment]
Regarding the copy/write: you might also want to save the `filterString`: in ` RcppPwiz::addSpectrumList` function you could add:
```r
Rcpp::StringVector filterString = spctr_header["filterString"];
```
and then in the loop, if the value is not `NA`:
```r
if (!Rcpp::is_na(filterString[i])) {
    spct.set(MS_filter_string, filterString[i]);
}
```

**Comment by sgibb** [comment]
@jotsetung thanks for your suggestion. I added the filter string to `addSpectrumList` but it doesn't solve the problem:
```
Running examples in ‘mzR-Ex.R’ failed
The error most likely occurred in:

> ### Name: copyWriteMSData
> ### Title: Write MS spectrum data to a MS file copying metadata from the
> ###   originating file
> ### Aliases: copyWriteMSData
> 
> ### ** Examples
> 
> ## Open a MS file and read the spectrum and header information
> library(msdata)
> fl <- system.file("threonine", "threonine_i2_e35_pH_tree.mzXML",
+     package = "msdata")
> ms_fl <- openMSfile(fl, backend = "pwiz")
> 
> ## Get the spectra
> pks <- spectra(ms_fl)
> ## Get the header
> hdr <- header(ms_fl)
> 
> ## Modify the spectrum data adding 100 to each intensity.
> pks <- lapply(pks, function(z) {
+     z[, 2] <- z[, 2] + 100
+     z
+ })
> 
> ## Copy metadata and additional information from the originating file
> ## and save it, along with the modified data, to a new mzML file.
> out_file <- tempfile()
> copyWriteMSData(pks, file = out_file, original_file = fl,
+     header = hdr)
Error in pwizModule$copyWriteMSfile(file, outformat, original_file, header,  : 
  Index out of bounds: [index='filterString'].
Calls: copyWriteMSData -> <Anonymous> -> .External
Execution halted
```

The Ramp interface fails with the following error (I just extended the `header` list):
```
Rdevel> source("test_filter_string.R")
Rdevel> test_filter_string()
Loading required package: Rcpp
Error in object@backend$getAllScanHeaderInfo() : 
  Could not convert using R function: as.data.frame.
Rdevel> traceback()
7: stop(list(message = "Could not convert using R function: as.data.frame.", 
       call = object@backend$getAllScanHeaderInfo(), cppstack = NULL))
6: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x5631c2209fd0>, 
       dll = list(name = "Rcpp", path = "/home/sebastian/opt/R/lib/R/library/Rcpp/libs/Rcpp.so", 
           dynamicLookup = TRUE, handle = <pointer: 0x5631c2ca40e0>, 
           info = <pointer: 0x5631c11dcf20>), numParameters = -1L), 
       <pointer: 0x5631c4567200>, <pointer: 0x5631c2d5dc60>, .pointer)
5: object@backend$getAllScanHeaderInfo()
4: .local(object, ...)
3: header(mzxml)
2: header(mzxml) at test_filter_string.R#17
1: test_filter_string()
Rdevel> 
```

Currently the `filterString` is converted into a `factor`. Should I call `res$filterString <- as.character(res$filterString)` (as for `spectrumId`) or do we want to use `stringsAsFactors=FALSE` in `RcppPwiz::getScanHeaderInfo`?

BTW: I fixed the `.travis.yml`. Now the build correctly fails.

**Comment by jotsetung** [comment]
Re `filterString` being a `factor`: I would indeed call `as.character` on the `filterString` too (since it is supposed to be a `NA_character_` or a `character`).

Re `[index='filterString']` error: there is the `.validateHeader` function in *functions-utils.R* that checks if the provided `header` argument is in the correct format. You would have to add `filterString = "character"` to the `req_cols` otherwise this column gets removed.

Re error in `Ramp`: the error is puzzling; you could add the `filterString` column in the `header,mzRamp` methods, not in the `getScanHeaderInfo` C++ function. That might help. The `spectrumId` column is also added in that method.

**Comment by sgibb** [comment]
@jotsetung thanks for your helpful comments. This PR now adds full `filterString` support.

> Re [index='filterString'] error: there is the .validateHeader function in functions-utils.R that checks if the provided header argument is in the correct format. You would have to add filterString = "character" to the req_cols otherwise this column gets removed.

Correct, I added it and the everything works as expected.

> Re error in Ramp: the error is puzzling; you could add the filterString column in the header,mzRamp methods, not in the getScanHeaderInfo C++ function. That might help. The spectrumId column is also added in that method.

I implemented it exactly this way. I thought before it is like cheating if we modify the output of the `Rcpp` code in `R` (if it could easily be done in `Rcpp`).

**Pull request merged**
