### PR TITLE
Remove CXX hack for travis-ci

### PR DESCRIPTION
**Pull request by sneumann**
Let's see if that builds on travis

### CODE REVIEW

**Comment by lgatto** [comment]
That magic hack is still necessary - in the mean time, I fixed the command in the travis file and it seems to work.

**Comment by lgatto** [comment]
Shit, I spoke too soon :-(

**Comment by sneumann** [comment]
The \n is still necessary to put multiple lines into the ` ~/.R/Makevars` Maybe they changed 
the underlying shell, and now we need `\\n` or other quoting magic . Trying via the pull request has the benefit 
that we can undo our attempts by not accepting the pull, and not clutter the commit history. 
I learned that the hard way ...

**Comment by lgatto** [comment]
How do you send a pull request? Do you have a clone, or another branch?

**Comment by lgatto** [comment]
We are building successfully again!

**Comment by sneumann** [comment]
Cool! Simplest way to pull request was editing on the github pages. Under the hood that creates a (temporary) branch.

**Pull request closed without merging**
