### PR TITLE
Pwiz upgrade

### PR DESCRIPTION
**Pull request by thirdwing**

### CODE REVIEW

**Comment by sneumann** [comment]
Wow, that was quick. But I need this not into master, but into devel,
which is the branch that is/should be synced with BioC SVN. 
I think I could master git alone, and SVN alone, but the BioC setup 
really confuses me.

**Comment by sneumann** [comment]
I *think* I have SVN and the github devel branch in Sync now,
so if the pull request points to devel this should work

**Comment by thirdwing** [comment]
I am still a little confused.

The BioC SVN is synced with devel brach, so what about master?

Right now I don't think we can merge the pwiz_upgrade branch into devel. The devel is out of sync.

**Comment by sneumann** [comment]
The other way around, master is way behind. Can one delete it, 
to avoid confusion ? I think semantically it should be the same as devel.

**Comment by thirdwing** [comment]
I agree.

Let's test the pwiz_upgrade branch first.

**Pull request closed without merging**
