### PR TITLE
Feature/update pwiz 3 0 21263

### LINKED ISSUE #250: Update pwiz code base
This has come up several times already (see #245 and [here](https://github.com/lgatto/MSnbase/issues/551)) - there seems to be a recurrent need to update the `pwiz` code base in `mzR`. I suggest that we compile our trials and errors (I know @sneumann had a go already) in this issue so that we avoid stumbling on the same rocks over and over again. 

cc @jorainer

### PR DESCRIPTION
**Pull request by sneumann**
Update to Proteowizard 3_0_21263
 Removed RAMP backend, dropping ability to read mzData

Closes #250, 
Revisit #247, #245, #235, #233, and maybe others.

### CODE REVIEW

**Comment by jorainer** [comment]
After having another though I think it makes sense to change the current behaviour of the `header` call and **always** return a `data.frame`. Also, since the CDF backend seems to always return a `data.frame` and also the (obsolete) Ramp backend returned always a `data.frame` - so mayby I added that *feature* at some point accidentally (?).

I would thus suggest to remove the lines:

```r
              if (length(scans) == 1) {
                  ## Convert data.frame to list to be conform with old code
                  res <- as.list(res)
              }
```

in the `setMethod("header", c("mzRpwiz", "numeric"),` method in the *methods-mzRpwiz.R* file. Do you agree @lgatto and @sneumann ? Could you eventually do that in this PR @sneumann ?

**Comment by lgatto** [comment]
Yes, I think the header should always be a `data.frame`.

**Comment by jorainer** [comment]
I'll make a PR to this branch, so no need to manually change anything @sneumann .

**Comment by jorainer** [comment]
PR #254 (into this branch) adds the above described changes (i.e. `header` always returning a `data.frame`).

**Comment by jorainer** [comment]
Hi @sneumann , with the recent changes I can install, but I get the following WARNINGS (which cause the github action to fail):

```
* checking for portable file names ... WARNING
Found the following file with a non-portable file name:
  src/boost/serialization/collection_size_type copy.hpp
These are not fully portable file names.
See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘mzR’ can be installed ... WARNING
Found the following significant warnings:
  pwiz/data/proteome/Modification.cpp:89:5: warning: 'auto_ptr<pwiz::chemistry::Formula>' is deprecated [-Wdeprecated-declarations]
  pwiz/utility/misc/TabReader.cpp:44:22: warning: assigning field to itself [-Wself-assign-field]
See ‘/Users/jo/Projects/git/jorainer/mzR.Rcheck/00install.out’ for details.
```

don't know if there is something that could be done for these.

**Comment by sneumann** [comment]
Hi, while the Warnings are a nuisance, I'd like to address the errors on all arches first. On Windows I get 
https://github.com/sneumann/mzR/runs/4342043079?check_suite_focus=true#step:20:2932
which sounds like quite some compiler complaints. Maybe @hechth might have an idea ?
Yours, Steffen

**Comment by hechth** [comment]
@sneumann Thanks for letting me know - from the log I can see that some macros are undefined or mapped to the wrong type, but this is not a very helpful. I' currently quite busy, so I can't promise when I will find the time to have a look at this.

**Comment by sneumann** [comment]
Hi, @uly55e5 offered to have a look, thanks David ! Yours, Steffen

**Comment by sneumann** [comment]
Hi, we got things to work on Windows (thanks @uly55e5 !) on the errors on macOS are a failure to set-up R-devel in the first place. It did work some time ago on macOS, we can hope it still does. SInce mzR on BioC devel is broken anyway, I'll merge now and we pick up the pieces from there. Yours, Steffen

**Pull request merged**
