### PR TITLE
compile pwiz when installing on Windows

### PR DESCRIPTION
**Pull request by lgatto**

### CODE REVIEW

**Comment by sneumann** [comment]
Hi, I am currently testing this on windows, the Makefile.win will currently not compile, patch coming up. Yours, Steffen

**Comment by lgatto** [comment]
Shit, just merged and committed. Keep me posted.

**Comment by sneumann** [comment]
Hi, I didn't get it to compile in the end. 
One required change is to use ./boost/thread/win32/thread.o \ 
instead of the pthread: 
./boost/thread/pthread/once.o \
./boost/thread/pthread/thread.o \
But I get 
``````
c:/Rtools/mingw_64/bin/g++  -std=c++0x -I"D:/ProgramFiles/R-3.3.1/include" -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I./boost -I. -DHAVE_PWIZ_MZML_LIB  -DWITHOUT_MZ5 -fpermissive -DWINDOWS_NATIVE     -I"D:/ProgramFiles/R-3.3.1/library/Rcpp/include" -I"D:/ProgramFiles/R-3.3.1/library/zlibbioc/include" -I"d:/local330/include" -c pwiz/utility/misc/Filesystem.cpp -o pwiz/utility/misc/Filesystem.o
pwiz/utility/misc/Filesystem.cpp:45:27: fatal error: sys/ioctl.h: No such file or directory
     #include <sys/ioctl.h>
                           ^
compilation terminated.
``````
possibly a -DWIN32 is required, not sure. Next I hit undefined symbols. Need to run,
yours,
Steffen

**Comment by lgatto** [comment]
@thirdwing - any idea?

**Comment by thirdwing** [comment]
This shouldn't be hard if we have time to test on windows.

**Comment by sneumann** [comment]
Hi, I have a version now that builds, will commit soon, 
but I get an `Error in inDL(x, as.logical(local), as.logical(now), ...) :
  can't load shared object 'D:/ProgramFiles/R-3.3.1/library/mzR/libs/x64/mzR.dll' :
  LoadLibrary failure:  module not found
`

**Comment by sneumann** [comment]
Hi, I comitted my version now, compiles but still fails on load.
Ideas, anyone ?
Yours, Steffen

````
** testing if installed package can be loaded
Error in inDL(x, as.logical(local), as.logical(now), ...) :
  kann shared object 'D:/ProgramFiles/R-3.3.1/library/mzR/libs/x64/mzR.dll' nicht laden:
  LoadLibrary failure:  Das angegebene Modul wurde nicht gefunden.

Fehler: Laden fehlgeschlagen
Ausführung angehalten
ERROR: loading failed
````

**Comment by sneumann** [comment]
The issue sounds a bit like 
http://stackoverflow.com/questions/13497222/the-specified-module-could-not-be-found-in-r
Can someone confirm the issue ?

**Comment by sneumann** [comment]
I am afraid we also have this `LoadLibrary failure:` on BioC
at https://bioconductor.org/checkResults/3.4/bioc-LATEST/mzR/tokay1-install.html
and same on https://win-builder.r-project.org/4yZYZq5Yhqri (will disappear in a few days)
Any ideas ?

**Comment by sneumann** [comment]
Hi, I tried a lot of variants, and finally tried the "Dependency Walker" mentioned in the stackoverflow 
mentioned above. It shows some errors, but I am stymed why the software I have installed 
that is completely unrelated to R is shown. I guess I am on a wrong lead. I need help by a windows expert.

unbenannt
Yours, Steffen

**Pull request merged**
